import type { Listing, ListingSummary } from '../models/listing';

const PHOTO = (seed: string) =>
  `https://images.unsplash.com/photo-${seed}?auto=format&fit=crop&w=1200&q=80`;

export const MOCK_LISTINGS: Listing[] = [
  {
    id: 'lst-001',
    title: 'Pulsar Thermion 2 XQ50 Pro',
    gearType: 'thermal',
    gearTypeLabel: 'Thermal',
    condition: 'mint',
    dailyRateCents: 14500,
    pickupZip: '80301',
    heroPhotoUrl: PHOTO('1611078489935-0cb964de46d6'),
    rating: { average: 4.9, count: 31 },
    listerName: 'Jess Park',
    listerVerified: true,
    description:
      'Top-tier 50mm thermal scope, used three seasons on coyote and hog hunts. Stored climate-controlled, batteries fresh, picatinny mount included.',
    photos: [
      { id: 'p-001-1', url: PHOTO('1611078489935-0cb964de46d6'), alt: 'Pulsar XQ50 mounted', isHero: true },
      { id: 'p-001-2', url: PHOTO('1572635148818-ef6fd45eb394'), alt: 'Optic side profile' },
      { id: 'p-001-3', url: PHOTO('1518709268805-4e9042af2176'), alt: 'In carry case' },
    ],
    specs: [
      { key: 'Resolution', value: '640×480' },
      { key: 'Detection range', value: '1,800 yd' },
      { key: 'Magnification', value: '2–16x' },
      { key: 'Weight', value: '32 oz' },
      { key: 'Battery life', value: '7 hr' },
    ],
    depositCents: 50000,
    serviceFeePct: 5,
    cancellationPolicy: 'moderate',
  },
  {
    id: 'lst-002',
    title: 'ATN X-Sight 4K Pro 5-20x',
    gearType: 'night-vision',
    gearTypeLabel: 'Night vision',
    condition: 'field-ready',
    dailyRateCents: 8500,
    pickupZip: '80525',
    heroPhotoUrl: PHOTO('1535381273077-21e815afe1ce'),
    rating: { average: 4.6, count: 18 },
    listerName: 'Tyler Reed',
    listerVerified: true,
    description:
      'Reliable digital NV scope with day/night dual mode. Some scuffs on the housing, glass and electronics flawless.',
    photos: [
      { id: 'p-002-1', url: PHOTO('1535381273077-21e815afe1ce'), isHero: true },
      { id: 'p-002-2', url: PHOTO('1518709268805-4e9042af2176') },
      { id: 'p-002-3', url: PHOTO('1593079831268-3381b0db4a77') },
    ],
    specs: [
      { key: 'Resolution', value: '4K Ultra HD sensor' },
      { key: 'Magnification', value: '5–20x' },
      { key: 'Detection range', value: '950 yd' },
      { key: 'Battery life', value: '18 hr' },
    ],
    depositCents: 25000,
    serviceFeePct: 5,
    cancellationPolicy: 'moderate',
  },
  {
    id: 'lst-003',
    title: 'AGM Rattler TS35-384 Thermal Scope',
    gearType: 'thermal',
    gearTypeLabel: 'Thermal',
    condition: 'mint',
    dailyRateCents: 9500,
    pickupZip: '80525',
    heroPhotoUrl: PHOTO('1593079831268-3381b0db4a77'),
    rating: { average: 5.0, count: 9 },
    listerName: 'Tyler Reed',
    listerVerified: true,
    description: 'Mint AGM Rattler 384x288 thermal scope. Multi-reticle, 1024x768 OLED display, 35 mm lens. Comes with hard case, charger, and remote.',
    photos: [
      { id: 'p-003-1', url: PHOTO('1593079831268-3381b0db4a77'), isHero: true },
      { id: 'p-003-2', url: PHOTO('1611078489935-0cb964de46d6') },
    ],
    specs: [
      { key: 'Resolution', value: '384×288' },
      { key: 'Detection range', value: '1,475 yd' },
      { key: 'Display', value: '1024×768 OLED' },
      { key: 'Battery life', value: '7 hr' },
    ],
    depositCents: 60000,
    serviceFeePct: 5,
    cancellationPolicy: 'strict',
  },
  {
    id: 'lst-004',
    title: 'Pulsar Axion 2 LRF XQ35 Pro Monocular',
    gearType: 'thermal',
    gearTypeLabel: 'Thermal',
    condition: 'field-ready',
    dailyRateCents: 6500,
    pickupZip: '82001',
    heroPhotoUrl: PHOTO('1611078489935-0cb964de46d6'),
    rating: { average: 4.7, count: 11 },
    listerName: 'Casey Morgan',
    listerVerified: true,
    description: 'Handheld thermal monocular with built-in laser rangefinder. Dialed in for scouting hogs at distance — fits in a chest pocket.',
    photos: [{ id: 'p-004-1', url: PHOTO('1611078489935-0cb964de46d6'), isHero: true }],
    specs: [
      { key: 'Resolution', value: '384×288' },
      { key: 'Detection range', value: '2,000 yd' },
      { key: 'Rangefinder', value: 'Up to 1,000 yd' },
      { key: 'Battery life', value: '11 hr' },
    ],
    depositCents: 40000,
    serviceFeePct: 5,
    cancellationPolicy: 'moderate',
  },
  {
    id: 'lst-005',
    title: 'Vortex Razor HD 27-60x85 Spotter',
    gearType: 'optics',
    gearTypeLabel: 'Optics',
    condition: 'mint',
    dailyRateCents: 4000,
    pickupZip: '80301',
    heroPhotoUrl: PHOTO('1518709268805-4e9042af2176'),
    rating: { average: 4.9, count: 14 },
    listerName: 'Jess Park',
    listerVerified: true,
    description: 'Angled spotting scope, premium HD glass, includes Vortex tripod and soft case.',
    photos: [{ id: 'p-005-1', url: PHOTO('1518709268805-4e9042af2176'), isHero: true }],
    specs: [
      { key: 'Magnification', value: '27–60x' },
      { key: 'Objective', value: '85mm' },
      { key: 'Eye relief', value: '16.7–17 mm' },
      { key: 'Weight', value: '65.6 oz' },
    ],
    depositCents: 20000,
    serviceFeePct: 5,
    cancellationPolicy: 'flexible',
  },
  {
    id: 'lst-006',
    title: 'Millennium M150 Treestand',
    gearType: 'tree-stand',
    gearTypeLabel: 'Treestand',
    condition: 'field-ready',
    dailyRateCents: 2000,
    pickupZip: '82001',
    heroPhotoUrl: PHOTO('1572635148818-ef6fd45eb394'),
    rating: { average: 4.5, count: 6 },
    listerName: 'Casey Morgan',
    listerVerified: true,
    description: 'Hang-on stand with sling seat. Light scuffs from use. Includes safety harness and lifeline.',
    photos: [{ id: 'p-006-1', url: PHOTO('1572635148818-ef6fd45eb394'), isHero: true }],
    specs: [
      { key: 'Capacity', value: '300 lb' },
      { key: 'Weight', value: '17 lb' },
      { key: 'Platform', value: '37" × 24"' },
    ],
    depositCents: 8000,
    serviceFeePct: 5,
    cancellationPolicy: 'flexible',
  },
  {
    id: 'lst-007',
    title: 'Mystery Ranch Metcalf 100 Pack',
    gearType: 'pack',
    gearTypeLabel: 'Pack',
    condition: 'mint',
    dailyRateCents: 2500,
    pickupZip: '80301',
    heroPhotoUrl: PHOTO('1551632811-561732d1e306'),
    rating: { average: 4.8, count: 7 },
    listerName: 'Jess Park',
    listerVerified: true,
    description: '100L expedition pack, Guide Light frame, used twice. Sized M/L torso.',
    photos: [{ id: 'p-007-1', url: PHOTO('1551632811-561732d1e306'), isHero: true }],
    specs: [
      { key: 'Volume', value: '6,100 cu in' },
      { key: 'Frame', value: 'Guide Light MT' },
      { key: 'Weight', value: '6 lb 9 oz' },
      { key: 'Torso', value: 'M / L' },
    ],
    depositCents: 12000,
    serviceFeePct: 5,
    cancellationPolicy: 'flexible',
  },
  {
    id: 'lst-008',
    title: 'Bundle: Pulsar Thermal + ATN NV Combo',
    gearType: 'thermal',
    gearTypeLabel: 'Bundle',
    condition: 'field-ready',
    dailyRateCents: 20000,
    pickupZip: '80525',
    heroPhotoUrl: PHOTO('1611078489935-0cb964de46d6'),
    rating: { average: 5.0, count: 4 },
    listerName: 'Tyler Reed',
    listerVerified: true,
    isBundle: true,
    description:
      'Thermal scope for daytime hog detection paired with NV scope for after-dark engagement. One pickup, one deposit, save 13% vs. booking separately.',
    photos: [
      { id: 'p-008-1', url: PHOTO('1611078489935-0cb964de46d6'), isHero: true },
      { id: 'p-008-2', url: PHOTO('1535381273077-21e815afe1ce') },
    ],
    specs: [
      { key: 'Includes', value: 'Pulsar XQ50 + ATN 4K Pro' },
      { key: 'Combined value', value: '$6,800' },
      { key: 'Bundle savings', value: '13% vs separate' },
    ],
    bundleListingIds: ['lst-001', 'lst-002'],
    depositCents: 75000,
    serviceFeePct: 5,
    cancellationPolicy: 'strict',
  },
  {
    id: 'lst-009',
    title: 'Pulsar Talion XQ35 Thermal Monocular',
    gearType: 'thermal',
    gearTypeLabel: 'Thermal',
    condition: 'field-ready',
    dailyRateCents: 7500,
    pickupZip: '80016',
    heroPhotoUrl: PHOTO('1593079831268-3381b0db4a77'),
    rating: { average: 4.4, count: 5 },
    listerName: 'Drew Walker',
    listerVerified: false,
    description: 'Handheld thermal monocular, perfect for scouting before a stand sit. Mild wear, fully functional.',
    photos: [{ id: 'p-009-1', url: PHOTO('1593079831268-3381b0db4a77'), isHero: true }],
    specs: [
      { key: 'Resolution', value: '384×288' },
      { key: 'Detection range', value: '1,400 yd' },
      { key: 'Battery life', value: '8 hr' },
    ],
    depositCents: 30000,
    serviceFeePct: 5,
    cancellationPolicy: 'moderate',
  },
  {
    id: 'lst-010',
    title: 'Sig Sauer Tango4 4-16x44',
    gearType: 'optics',
    gearTypeLabel: 'Optics',
    condition: 'battle-scarred',
    dailyRateCents: 3500,
    pickupZip: '82001',
    heroPhotoUrl: PHOTO('1572635148818-ef6fd45eb394'),
    rating: { average: 4.2, count: 8 },
    listerName: 'Casey Morgan',
    listerVerified: true,
    description: 'Has seen real use — turret rings worn but tracking is true. Glass clear. Honest workhorse.',
    photos: [{ id: 'p-010-1', url: PHOTO('1572635148818-ef6fd45eb394'), isHero: true }],
    specs: [
      { key: 'Magnification', value: '4–16x' },
      { key: 'Objective', value: '44mm' },
      { key: 'Reticle', value: 'MOA Milling' },
    ],
    depositCents: 10000,
    serviceFeePct: 5,
    cancellationPolicy: 'flexible',
  },
  {
    id: 'lst-011',
    title: 'InfiRay Bolt TH50C V2 Clip-On Thermal',
    gearType: 'thermal',
    gearTypeLabel: 'Thermal',
    condition: 'mint',
    dailyRateCents: 9000,
    pickupZip: '80301',
    heroPhotoUrl: PHOTO('1611078489935-0cb964de46d6'),
    rating: { average: 4.9, count: 12 },
    listerName: 'Jess Park',
    listerVerified: true,
    description: 'Clip-on thermal that pairs with your existing daytime scope. 640×512 sensor, picatinny mount included. Try-before-you-buy a clip-on without committing $5k.',
    photos: [{ id: 'p-011-1', url: PHOTO('1611078489935-0cb964de46d6'), isHero: true }],
    specs: [
      { key: 'Resolution', value: '640×512' },
      { key: 'Detection range', value: '2,400 yd' },
      { key: 'Refresh rate', value: '50 Hz' },
      { key: 'Weight', value: '24 oz' },
    ],
    depositCents: 75000,
    serviceFeePct: 5,
    cancellationPolicy: 'strict',
  },
  {
    id: 'lst-012',
    title: 'Nocpix ACE H50R LRF Thermal Monocular',
    gearType: 'thermal',
    gearTypeLabel: 'Thermal',
    condition: 'mint',
    dailyRateCents: 8000,
    pickupZip: '80525',
    heroPhotoUrl: PHOTO('1593079831268-3381b0db4a77'),
    rating: { average: 5.0, count: 6 },
    listerName: 'Tyler Reed',
    listerVerified: true,
    description: 'Premium handheld thermal with built-in laser rangefinder. Picks coyotes at 800 yards in moderate humidity.',
    photos: [{ id: 'p-012-1', url: PHOTO('1593079831268-3381b0db4a77'), isHero: true }],
    specs: [
      { key: 'Resolution', value: '640×512' },
      { key: 'Detection range', value: '2,200 yd' },
      { key: 'Rangefinder', value: 'Up to 1,200 yd' },
      { key: 'Battery life', value: '10 hr' },
    ],
    depositCents: 50000,
    serviceFeePct: 5,
    cancellationPolicy: 'moderate',
  },
  {
    id: 'lst-013',
    title: 'Leupold Mark 5HD 5-25x56',
    gearType: 'optics',
    gearTypeLabel: 'Optics',
    condition: 'mint',
    dailyRateCents: 5500,
    pickupZip: '80525',
    heroPhotoUrl: PHOTO('1518709268805-4e9042af2176'),
    rating: { average: 4.9, count: 7 },
    listerName: 'Tyler Reed',
    listerVerified: true,
    description: 'Long-range first focal plane scope. PR1 reticle, zero stop, throw lever installed.',
    photos: [{ id: 'p-013-1', url: PHOTO('1518709268805-4e9042af2176'), isHero: true }],
    specs: [
      { key: 'Magnification', value: '5–25x' },
      { key: 'Objective', value: '56mm' },
      { key: 'Reticle', value: 'PR1-MOA' },
      { key: 'Tube', value: '35mm' },
    ],
    depositCents: 35000,
    serviceFeePct: 5,
    cancellationPolicy: 'strict',
  },
  {
    id: 'lst-014',
    title: 'Eberlestock X3 Hunting Pack',
    gearType: 'pack',
    gearTypeLabel: 'Pack',
    condition: 'field-ready',
    dailyRateCents: 1800,
    pickupZip: '82001',
    heroPhotoUrl: PHOTO('1551632811-561732d1e306'),
    rating: { average: 4.6, count: 5 },
    listerName: 'Casey Morgan',
    listerVerified: true,
    description: 'Mid-size day pack with reinforced scope sleeve and meat shelf. Light fabric pilling, all zippers and buckles solid.',
    photos: [{ id: 'p-014-1', url: PHOTO('1551632811-561732d1e306'), isHero: true }],
    specs: [
      { key: 'Volume', value: '1,830 cu in' },
      { key: 'Weight', value: '4.5 lb' },
      { key: 'Scope sleeve', value: 'Yes' },
    ],
    depositCents: 6000,
    serviceFeePct: 5,
    cancellationPolicy: 'flexible',
  },
  {
    id: 'lst-015',
    title: 'Tethrd Phantom Saddle Kit',
    gearType: 'tree-stand',
    gearTypeLabel: 'Saddle',
    condition: 'mint',
    dailyRateCents: 2200,
    pickupZip: '80016',
    heroPhotoUrl: PHOTO('1572635148818-ef6fd45eb394'),
    rating: { average: 4.7, count: 3 },
    listerName: 'Drew Walker',
    listerVerified: false,
    description: 'Lightweight saddle with platform, lineman belt, and tether. Compact alternative to a treestand.',
    photos: [{ id: 'p-015-1', url: PHOTO('1572635148818-ef6fd45eb394'), isHero: true }],
    specs: [
      { key: 'Weight', value: '2.6 lb' },
      { key: 'Capacity', value: '300 lb' },
      { key: 'Includes', value: 'Saddle, platform, tether, lineman' },
    ],
    depositCents: 9000,
    serviceFeePct: 5,
    cancellationPolicy: 'moderate',
  },
];

export const MOCK_LISTING_SUMMARIES: ListingSummary[] = MOCK_LISTINGS.map(
  ({ description, photos, specs, depositCents, serviceFeePct, cancellationPolicy, bundleListingIds, ...summary }) => summary,
);

export const listingById = (id: string): Listing | undefined =>
  MOCK_LISTINGS.find((l) => l.id === id);
