import type { AppNotification } from '../models/notification';

export const MOCK_NOTIFICATIONS: AppNotification[] = [
  {
    id: 'n-001',
    kind: 'booking-confirmed',
    title: 'Booking confirmed',
    body: 'Jess Park approved your request for the Pulsar Thermion 2 XQ50, May 12–15.',
    createdAt: '2026-04-22T18:11:00Z',
    read: true,
    link: '/booking/bk-001',
  },
  {
    id: 'n-002',
    kind: 'message',
    title: 'New message from Tyler Reed',
    body: 'Battery topped off — should last the whole sit.',
    createdAt: '2026-04-28T07:30:00Z',
    read: false,
    link: '/dashboard/messages?thread=th-002',
  },
  {
    id: 'n-003',
    kind: 'booking-reminder',
    title: 'Pickup tomorrow',
    body: 'Pulsar Thermion 2 XQ50 — Boulder REI, 7:30 AM. Bring photo ID.',
    createdAt: '2026-04-30T19:00:00Z',
    read: false,
    link: '/booking/bk-001',
  },
  {
    id: 'n-004',
    kind: 'review-received',
    title: 'You have a new review',
    body: 'Avery Stone left a 5-star review on your Pulsar Thermion listing.',
    createdAt: '2026-03-25T20:14:00Z',
    read: true,
    link: '/dashboard/reviews',
  },
  {
    id: 'n-005',
    kind: 'payout-released',
    title: 'Payout sent',
    body: '$120.38 sent to your bank account ending in 4421.',
    createdAt: '2026-03-24T03:00:00Z',
    read: true,
    link: '/dashboard/earnings',
  },
  {
    id: 'n-006',
    kind: 'dispute',
    title: 'Dispute opened',
    body: 'Robin Cole opened a dispute on the Sig Sauer Tango4 booking.',
    createdAt: '2026-04-06T09:30:00Z',
    read: false,
    link: '/dashboard/bookings/bk-006',
  },
  {
    id: 'n-007',
    kind: 'system',
    title: 'Verification required',
    body: 'Complete identity verification before publishing additional listings.',
    createdAt: '2026-04-15T11:00:00Z',
    read: false,
    link: '/dashboard/setup-onboarding',
  },
];
